info:
  app:
    name: BackFeYConsuelo
    version: @project.version@

spring:
  #profiles:
  #  active: local
  application:
    name: ${info.app.name}
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    banner-mode: "off"
  jackson:
    default-property-inclusion: non_null
  config-cors:
    allowed-origins: "*"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "Content-Type,Access-Control-Allow-Origin,Access-Control-Allow-Headers,Authorization"
    max-age: 3600

# configuracion del swagger
swagger:
  app:
    title: 'BackFeYConsuelo REST Service'
    description: 'REST CRUD operations over musician'

# configuracion para el token JWT
jwt-config:
  expiration-time: 15 # 15 minutos para la expìracion del token
  secret-key: ${TOKEN_SECRET_KEY}

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres

server:
  port: 8082

logging:
  config: null
  level:
    ROOT: INFO
    com:
      madiva: INFO
    org:
      hibernate:
        SQL: ERROR
        type:
          descriptor:
            sql:
              BasicBinder: ERROR

# configuracion para el token JWT
jwt-config:
  expiration-time: 600 # en local ponemos un tiempo de expiracion grande
  secret-key: '21aa16b1b41b33d7018fcdeabdbc7ea91000dabfb03cfdd9f4f0f07c6634ae8f'

---

spring:
  config:
    activate:
      on-profile: pro

