info:
  app:
    name: BackFeYConsuelo
    version: @project.version@

spring:
  #profiles:
  #  active: local
  application:
    name: ${info.app.name}
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    banner-mode: "off"
  jackson:
    default-property-inclusion: non_null
  config-cors:
    allowed-origins: "*"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "Content-Type,Access-Control-Allow-Origin,Access-Control-Allow-Headers,Authorization"
    max-age: 3600

feyconsuelo:
  swagger:
    app:
      title: 'BackFeYConsuelo REST Service'
      description: 'REST CRUD operations over musician'

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres

server:
  port: 8082

logging:
  config: null
  level:
    ROOT: INFO
    com:
      madiva: INFO
    org:
      hibernate:
        SQL: ERROR
        type:
          descriptor:
            sql:
              BasicBinder: ERROR

---

spring:
  config:
    activate:
      on-profile: pro

