version: '3.7'

services:
  servicedictionary-web:
    image: com.madiva/servicedictionary-web:latest
    build: .
    volumes:
      - ~/.aws:/root/.aws/
    expose:
      - 8001
    ports:
      - 8081:8081
      - 8001:8001
    environment:
      - SPRING_PROFILES_ACTIVE=local
    # Para hacer debug del arranque de spring boot cambiar "suspend=y" y conectar
    entrypoint: java -Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=8001,suspend=n -jar app.jar