openapi: 3.0.0
info:
  title: FeYConsuelo REST Service
  description: Backend para gestión de Fe y Consuelo
  contact:
    name: Eduardo Sanchez Bonilla
    email: eduardosanchezbonilla@gmail.com
  license:
    name: Apache License Version 2.0
  version: '1.0'
servers:
  - url: http://localhost:8082
    description: Generated server url
tags:
  - name: musician-delete-controller
    description: Musician delete operations
  - name: musician-insert-controller
    description: Musician insert operations
  - name: musician-get-controller
    description: Musician get operations
  - name: musician-update-controller
    description: Musician update operations
  - name: musician-query-controller
    description: Musician query operations
paths:
  "/musician":
    get:
      tags:
        - musician-get-controller
      summary: Returns all the musician registers from the database
      operationId: getAllMusicians
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/MusicianResponseDTO"
        '204':
          description: No content
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
    put:
      tags:
        - musician-update-controller
      summary: Update any data for a musician register in the database
      operationId: updateMusician
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/MusicianDTO"
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/MusicianResponseDTO"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
    post:
      tags:
        - musician-insert-controller
      summary: Add a new musician register to the database
      operationId: postMusician
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/MusicianDTO"
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/MusicianResponseDTO"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
  "/musician/{musicianId}":
    get:
      tags:
        - musician-get-controller
      summary: Returns the musician register from the database
      operationId: getMusician
      parameters:
        - name: musicianId
          in: path
          description: Musician Id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/MusicianResponseDTO"
        '204':
          description: No content
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
    delete:
      tags:
        - musician-delete-controller
      summary: Delete a musician register from the database
      operationId: deleteMusician
      parameters:
        - name: musicianId
          in: path
          description: Musician Id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
  "/musician/valueoutput":
    get:
      tags:
        - musician-query-controller
      summary: Returns the output value of a provider given an input value
      operationId: getValueOutput
      parameters:
        - name: domain
          in: query
          description: Domain
          required: true
          schema:
            type: string
        - name: subdomain
          in: query
          description: Subdomain
          required: true
          schema:
            type: string
        - name: provider_input
          in: query
          description: Input provider
          required: true
          schema:
            type: string
        - name: provider_output
          in: query
          description: Output provider
          required: true
          schema:
            type: string
        - name: value_input
          in: query
          description: Input value
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ValueOutputResponseDTO"
        '204':
          description: No content
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
  "/musician/find":
    get:
      tags:
        - musician-get-controller
      summary: Returns the musician registers from the database
      operationId: findMusicianRegistries
      parameters:
        - name: domain
          in: query
          description: Domain
          required: false
          schema:
            type: string
        - name: subdomain
          in: query
          description: Subdomain
          required: false
          schema:
            type: string
        - name: provider_input
          in: query
          description: Input provider
          required: false
          schema:
            type: string
        - name: provider_output
          in: query
          description: Output provider
          required: false
          schema:
            type: string
        - name: value_input
          in: query
          description: Input value
          required: false
          schema:
            type: string
        - name: value_output
          in: query
          description: Output value
          required: false
          schema:
            type: string
        - name: description
          in: query
          description: Description
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/MusicianResponseDTO"
        '204':
          description: No content
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
components:
  schemas:
    MusicianDTO:
      required:
        - domain
        - provider_input
        - provider_output
        - subdomain
        - value_input
        - value_output
      type: object
      properties:
        domain:
          type: string
          description: Domain
          example: CAR
        subdomain:
          type: string
          description: Subdomain
          example: BODYWORK
        provider_input:
          type: string
          description: Input provider
          example: OZONE
        provider_output:
          type: string
          description: Output provider
          example: MADIVA
        value_input:
          type: string
          description: Input value
          example: FAMILY
        value_output:
          type: string
          description: Output value
          example: FAMILIAR
        description:
          type: string
          description: Description
          example: TOYOTA
      description: Musician data
    MusicianResponseDTO:
      required:
        - domain
        - provider_input
        - provider_output
        - subdomain
        - value_input
        - value_output
      type: object
      properties:
        domain:
          type: string
          description: Domain
          example: CAR
        subdomain:
          type: string
          description: Subdomain
          example: BODYWORK
        id:
          type: string
          description: Identifier
          example: '1'
        provider_input:
          type: string
          description: Input provider
          example: OZONE
        provider_output:
          type: string
          description: Output provider
          example: MADIVA
        value_input:
          type: string
          description: Input value
          example: FAMILY
        value_output:
          type: string
          description: Output value
          example: FAMILIAR
        description:
          type: string
          description: Description
          example: TOYOTA
    ValueOutputResponseDTO:
      required:
        - value_output
      type: object
      properties:
        value_output:
          type: string
          description: Output value
          example: FAMILIAR
    ErrorDTO:
      required:
        - message
      type: object
      properties:
        code:
          type: string
          description: Error code
          example: '400'
        name:
          type: string
          description: Error name
          example: 'Bad Request'
        message:
          type: string
          description: Error message
          example: 'Bad Request'